### ISSUE TITLE
Publish from CI

### ISSUE THREAD

**Issue by Boshen** [oxc-project/coc-oxc#1]
Please let me know when this is ready to publish :grin:

**Comment by rzvxa** [comment]
Sure, Em this is awkward. I forgot to ask before creating this repo.

Do we want to keep all editor extensions in the main repo `oxc/editors` or was it this way to have access to the cargo project for the build process?

If having all editor extensions in the main mono repo was intentional let me know so I can remove this repo and move to the main mono repo.

**Comment by rzvxa** [comment]
@Boshen It is almost ready to publish; Can you give your thoughts on my last comment?

And would you give it a spin?

Just clone the project and add this to your `init.vim`

```vim
set runtimepath^=path/to/coc-oxc
```

**Comment by Boshen** [comment]
It's undecided where I want to keep all the editor integrations, but I'm leaning towards having the main repo a pure Rust monorepo instead of mixing 2 monorepo setups ...

I'll get into this once I clear out all my other tasks, which is a lot 😅

**Comment by rzvxa** [comment]
> It's undecided where I want to keep all the editor integrations, but I'm leaning towards having the main repo a pure Rust monorepo instead of mixing 2 monorepo setups ...

I'm also in favor of keeping the main repo in pure Rust. Maybe we should extract the `editors/vscode` to something like `oxc-project/oxc-vscode`?

> I'll get into this once I clear out all my other tasks, which is a lot 😅

Take your time; I'll try to add the publish ci while you are taking care of those.

**Comment by Boshen** [comment]
I'll take a look at "Github Organization Secrets" tomorrow so we can share all the publish keys.

**Comment by rzvxa** [comment]
@Boshen Could you figure out the GitHub organization secrets? It'll be cool if we release this plugin.

**Comment by Boshen** [comment]
`NPM_TOKEN` should work. It's being used here https://github.com/oxc-project/oxc-node/blob/eae0d0ad11ff730f66c28c832e8d47ef2a9f056e/.github/workflows/CI.yml#L459

**Comment by rzvxa** [comment]
closed via #10
https://www.npmjs.com/package/coc-oxc
